standard = "2008"

[libraries]
proj.files = [
	"./proj/src/**/**/*.vhd",
	"./proj/test/**/**/*.vhd",
	"./proj/src/**/**/**/*.vhd",
	"./proj/test/**/**/**/*.vhd",
	"./proj/src/**/**/**/**/*.vhd",
	"./proj/test/**/**/**/**/*.vhd",
	"./proj/src/**/**/**/**/**/*.vhd"
]
	
[lint]
unused = 'error' # Upgrade the 'unused' diagnostic to the 'error' severity
unnecessary_work_library = false # Disable linting for the 'library work;' statement
