[libraries]

lib.files = [
"proj/src/*.vhd",
"proj/src/**/*.vhd",
"proj/test/*.vhd",
"proj/test/**/*.vhd",
"proj/src/**/**/*.vhd",
"proj/test/**/**/*.vhd",
"proj/src/**/**/**/*.vhd",
"proj/test/**/**/**/*.vhd",
"proj/src/**/**/**/**/*.vhd",
"proj/test/**/**/**/**/*.vhd",
"proj/src/**/**/**/**/**/*.vhd",
"proj/test/**/**/**/**/**/*.vhd",
]
