[libraries]
standard = "2008"
ieee.files = [
	"~/dotfiles/ghdl/libraries/ieee/*.vhd",
]
ieee.is_third_party = true
	
lib.files = [
	"proj/src/*.vhd",
	"proj/src/**/*.vhd",
	"proj/test/*.vhd",
	"proj/test/**/*.vhd",
	"proj/src/**/**/*.vhd",
	"proj/test/**/**/*.vhd",
	"proj/src/**/**/**/*.vhd",
	"proj/test/**/**/**/*.vhd",
	"proj/src/**/**/**/**/*.vhd",
	"proj/test/**/**/**/**/*.vhd",
	"proj/src/**/**/**/**/**/*.vhd",
	"proj/test/**/**/**/**/**/*.vhd",
]


[lint]
unused = 'error' # Upgrade the 'unused' diagnostic to the 'error' severity
unnecessary_work_library = false # Disable linting for the 'library work;' statement
